# Generated by Django 4.2.7 on 2023-12-17 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_logentry_user_id_logentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_on', models.DateTimeField(auto_now_add=True)),
                ('movie_series_id', models.CharField(max_length=100)),
                ('movie_series_title', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
