# Generated by Django 4.2.7 on 2023-12-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_watcheditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcheditem',
            name='watched_on',
            field=models.DateTimeField(),
        ),
    ]
